# Generated by Django 6.0.3 on 2026-03-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_eventlocation_attendancerecord_face_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
